Pedagogy/Models/LogInManager/CaptchaResponseViewModel.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace Pedagogy.Models.LoginManager
{
    public class CaptchaResponseViewModel
    {
        public bool Success { get; set; }

        [JsonProperty(PropertyName = "error-codes")]
        public IEnumerable<string> ErrorCodes { get; set; }

        [JsonProperty(PropertyName = "challenge_ts")]
        public DateTime ChallengeTime { get; set; }

        public string HostName { get; set; }
        public double Score { get; set; }
        public string Action { get; set; }
    }
}

Pedagogy/Models/LogInManager/LogInViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Pedagogy.Models.LoginManager
{
    public class LoginViewModel : BaseViewModel
    {
        [Required(ErrorMessage = "The User name cannot be empty.")]
        [DisplayName("User name")]
        public string UserName { get; set; }

        [Required(ErrorMessage = "The Password cannot be empty.")]
        [DataType(DataType.Password)]
        [DisplayName("Password")]
        public string Password { get; set; }

        [DisplayName("Remember Me")]
        public bool RememberMe { get; set; }

        public string CheckEmailMsg { get; set; }
    }
}

Pedagogy/Models/LogInManager/RegisterViewModel.cs
using Pedagogy.Models.ClassMembers;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Pedagogy.Models.LoginManager
{
    public class RegisterViewModel : BaseViewModel
    {
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "The Password cannot be empty.")]
        [DisplayName("Password")]
        [MaxLength(50, ErrorMessage = "The Password cannot be longer than 50 characters.")]
        [RegularExpression(@"^(?=.{8,}$)(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9]).*$", ErrorMessage = "The password doesn't meet the requirements.")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [DisplayName("Password Confirmation")]
        [MaxLength(50, ErrorMessage = "The Password cannot be longer than 50 characters.")]
        [System.ComponentModel.DataAnnotations.Compare("Password", ErrorMessage = "The entered passwords do not match.")]
        public string PasswordConfirmation { get; set; }

        [Required(ErrorMessage = "The First name cannot be empty.")]
        [DisplayName("First Name")]
        [MaxLength(25, ErrorMessage = "The First name cannot be longer than 25 characters.")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "The Last name cannot be empty.")]
        [DisplayName("Last Name")]
        [MaxLength(25, ErrorMessage = "The Last name cannot be longer than 25 characters.")]
        public string LastName { get; set; }

        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "The Email address cannot be empty.")]
        [DisplayName("Email Address")]
        [EmailAddress(ErrorMessage = "Invalid email address.")]
        [MaxLength(320, ErrorMessage = "The Email address cannot be longer than 320 characters.")]
        public string Email { get; set; }

        [DataType(DataType.EmailAddress)]
        [DisplayName("Confirm Email")]
        [Required(ErrorMessage = "The confirm email cannot be empty.")]
        [System.ComponentModel.DataAnnotations.Compare("Email", ErrorMessage = "The entered emails do not match.")]
        public string ConfirmEmail { get; set; }

        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Phone Number")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Not a valid phone number")]
        public string PhoneNumber { get; set; }

        public FacilityViewModel CorporateInfo { get; set; }

        public Pedagogy.ClassMembers.Contact ContactInfo { get; set; }

        [DisplayName("State")]
        public int StateID { get; set; }

        public SelectList States { get; set; }

        public string GoogleCaptchaToken { get; set; }

        [Required(ErrorMessage = "Please select Facility or Corporation")]
        public string RegistrationType { get; set; }

        [Display(Name = "Website URL")]
        public string WebsiteURL { get; set; }
        public bool NoApplicableCorporation { get; set; }

        [Display(Name = "Parent Corporation Name")]
        public string ParentCorporationName { get; set; }

        public bool DefaultPassword { get; set; }
    }
}

Pedagogy/Models/LogInManager/RequestPasswordResetViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Pedagogy.Models.LoginManager
{
    public class RequestPasswordResetViewModel : BaseViewModel
    {
        [Required(ErrorMessage = "The Email address cannot be empty.")]
        [DisplayName("Email")]
        [EmailAddress(ErrorMessage = "Please enter a valid email address")]
        [MaxLength(200, ErrorMessage = "The Email cannot be longer than 200 characters.")]
        public string Email { get; set; }

        public string UserNotFoundErrMsg { get; set; }
        public string CheckEmailMsg { get; set; }
    }
}

Pedagogy/Models/LogInManager/ResetPasswordViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Pedagogy.Models.LoginManager
{
    public class ResetPasswordViewModel : BaseViewModel
    {
        public int UserId { get; set; }
        public string Token { get; set; }

        [DataType(DataType.Password)]
        [Required(ErrorMessage = "The Password cannot be empty.")]
        [DisplayName("Password")]
        [MaxLength(100, ErrorMessage = "The Password cannot be longer than 100 characters.")]
        [RegularExpression(@"^(?=.{8,}$)(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*\W).*$", ErrorMessage = "Password must include..<ul class='password-validation-err'><li>at least 8 characters</li><li>at least 1 numeric digit</li><li>at least 1 special character</li><li>1 uppercase letter</li><li>at least 1 lowercase letter</li></ul>")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [DisplayName("Password confirmation")]
        [MaxLength(100, ErrorMessage = "The Password cannot be longer than 100 characters.")]
        [Compare("Password", ErrorMessage = "The entered passwords do not match.")]
        public string PasswordConfirmation { get; set; }
    }
}

Pedagogy/Controllers/LogInManagerController.cs
using System;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using System.Net.Http;
using System.Collections.Generic;

using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;

using Kentico.Membership;
using Kentico.Web.Mvc;
using Kentico.PageBuilder.Web.Mvc;
using CMS.EventLog;
using CMS.Ecommerce;
using CMS.Membership;
using CMS.Globalization;
using CMS.Helpers;
using CMS.Localization;
using CMS.SiteProvider;
using CMS.DataEngine;
using CMS.CustomTables;
using CMS.CustomTables.Types.Pedagogy;
using CMS.DocumentEngine;

using DynamicRouting.Interfaces;

using Pedagogy.Models.LoginManager;
using Pedagogy.DataAccess.Dto;
using Pedagogy.DataAccess.DependencyInjection;
using Pedagogy.Models;
using Pedagogy.Lib.Helpers;
using Pedagogy.ClassMembers.DependencyInjection;
using Pedagogy.ClassMembers.Entities.Contact;

using Newtonsoft.Json;
using Pedagogy.ClassMembers.Entities.Facility;

namespace Pedagogy.Controllers
{
    public class LoginManagerController : BaseController
    {
        private IDynamicRouteHelper mDynamicRouteHelper;
        private IShoppingService mShoppingService;
        private readonly IClassMemberDependencies ClassMemberDependencies;

        public LoginManagerController(IDataDependencies dependencies, IShoppingService iss, IDynamicRouteHelper drh, IClassMemberDependencies classMemberDependencies) 
            : base(dependencies) 
        { 
            mShoppingService = iss; 
            mDynamicRouteHelper = drh;
            ClassMemberDependencies = classMemberDependencies;
        }

        //Provides access to the Kentico.Membership.SignInManager instance
        public SignInManager SignInManager => HttpContext.GetOwinContext().Get<SignInManager>();

        //Provides access to the Microsoft.Owin.Security.IAuthenticationManager instance.
        public IAuthenticationManager AuthenticationManager => HttpContext.GetOwinContext().Authentication;

        //Provides access to the Kentico.Membership.UserManager instance.
        public UserManager UserManager => HttpContext.GetOwinContext().Get<UserManager>();

        //Basic aciton that displays the sign-in form.
        public ActionResult Login()
        {
            string checkEmailMsg = (string)TempData["confirmEmailMsg"];

            var page = mDynamicRouteHelper.GetPage() as TreeNode;

            var model = GetBaseViewModel(new BaseDto(page),
            new LoginViewModel
            {
                CheckEmailMsg = !string.IsNullOrEmpty(checkEmailMsg) ? checkEmailMsg : ""
            });

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public async Task<ActionResult> Login(BaseViewModel<LoginViewModel> model, string baseNodeJson, string returnUrl)
        {
            model.BaseNodeData = JsonConvert.DeserializeObject<BaseDto>(baseNodeJson);

            //Validates the received user credentials based on the view model
            if (!ModelState.IsValid)
            {
                //Displays the sign-in form if the user credentials are invalid
                return View(model);
            }

            //Attemps to authenticate the user against the Kentico database
            SignInStatus logInResult = SignInStatus.Failure;
            try
            {
                logInResult = await SignInManager.PasswordSignInAsync(model.ViewModel.UserName, model.ViewModel.Password, model.ViewModel.RememberMe, false);
            }
            catch (Exception ex)
            {
                EventLogProvider.LogException("LogInManagerController", "ERROR", ex);
            }

            //If the authentication was not successful, displays the sign-in form with an "Authentication failed" message
            if (logInResult != SignInStatus.Success)
            {
                if (logInResult == SignInStatus.LockedOut)
                {
                    ModelState.AddModelError(String.Empty, ResHelper.GetString("LoginManager.WaitingForApprovalMsg", LocalizationContext.CurrentCulture.CultureCode, true));
                }
                if (logInResult == SignInStatus.Failure)
                {
                    ModelState.AddModelError(String.Empty, ResHelper.GetString("LoginManager.LoginFailureMsg", LocalizationContext.CurrentCulture.CultureCode, true));
                }
                return View(model);
            }

            var user = UserInfoProvider.GetUserInfo(model.ViewModel.UserName);
            user.LastLogon = DateTime.Now;
            user.Update();

            var customer = CustomerInfoProvider.GetCustomerInfoByUserID(user.UserID);
            if (customer == null)
            {
                customer = CustomerHelper.MapToCustomer(user);
            }
            mShoppingService.SetCustomer(customer);

            int? studentType = ClassMemberDependencies.ContactTypeRepo.GetContactTypeIDByCodeName(ContentIdentifiers.STUDENT_CODE_NAME);
            var student = ClassMemberDependencies.ContactRepo.GetContact(user?.UserID, studentType, x => new ContactDto { ContactID = x.ContactID });

            if (student != null)
            {
                if (CookieHelper.GetExistingCookie(ContentIdentifiers.STUDENT_ID_COOKIE) != null) CookieHelper.Remove(ContentIdentifiers.STUDENT_ID_COOKIE);

                HttpCookie cookie = new HttpCookie(ContentIdentifiers.STUDENT_ID_COOKIE)
                {
                    Value = student.ContactID.ToString()
                };

                Response.Cookies.Add(cookie);
            }

            //If authentication was successful, redirects to the return URL when possible or to a different default action
            var decodedReturnUrl = Server.UrlDecode(returnUrl);
            if (!string.IsNullOrEmpty(decodedReturnUrl) && Url.IsLocalUrl(decodedReturnUrl))
            {
                return Redirect(decodedReturnUrl);
            }

            return Redirect(ContentIdentifiers.DASHBOARD);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SignOut()
        {
            // remove all custom data columns and cookies
            if (CookieHelper.GetValue(ContentIdentifiers.STUDENT_ID_COOKIE) != null) CookieHelper.Remove(ContentIdentifiers.STUDENT_ID_COOKIE);
            if (CookieHelper.GetValue(ContentIdentifiers.FACILITY_ID_COOKIE) != null) CookieHelper.Remove(ContentIdentifiers.FACILITY_ID_COOKIE);
            if (CookieHelper.GetValue(ContentIdentifiers.CURRENT_USERNAME_COOKIE) != null) CookieHelper.Remove(ContentIdentifiers.CURRENT_USERNAME_COOKIE);
            if (CookieHelper.GetValue(ContentIdentifiers.MEMBERSHIP_CATEGORY_COOKIE) != null) CookieHelper.Remove(ContentIdentifiers.MEMBERSHIP_CATEGORY_COOKIE);

            var currentCart = mShoppingService.GetCurrentShoppingCart();
            currentCart.ShoppingCartCustomData.TryGetValue(ContentIdentifiers.MEMBERSHIP_PURCHASE_CUSTOM_DATA_COLUMN, out object mem);

            if (mem != null)
            {
                currentCart.ShoppingCartCustomData.Remove(ContentIdentifiers.MEMBERSHIP_PURCHASE_CUSTOM_DATA_COLUMN);
                currentCart.Update();
            }

            currentCart.ShoppingCartCustomData.TryGetValue(ContentIdentifiers.MEMBERSHIP_QTY_CUSTOM_DATA_COLUMN, out object memPurchase);
            if (memPurchase != null)
            {
                currentCart.ShoppingCartCustomData.Remove(ContentIdentifiers.MEMBERSHIP_QTY_CUSTOM_DATA_COLUMN);
                currentCart.Update();
            }

            mShoppingService.RemoveAllItemsFromCart();

            AuthenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
                        
            return Redirect(ContentIdentifiers.LOGIN_PAGE);
        }

        public ActionResult Register()
        {
            var page = mDynamicRouteHelper.GetPage() as TreeNode;

            HttpContext.Kentico().PageBuilder().Initialize(page.DocumentID);

            var model = GetBaseViewModel(new BaseDto(page), new RegisterViewModel { });

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public async Task<ActionResult> Register(BaseViewModel<RegisterViewModel> model, string baseNodeJson)
        {
            model.BaseNodeData = JsonConvert.DeserializeObject<BaseDto>(baseNodeJson);

            var page = mDynamicRouteHelper.GetPage();

            //Validates the received user data based on the view model
            if (!ModelState.IsValid)
            {
                HttpContext.Kentico().PageBuilder().Initialize(page.DocumentID);

                return View(model);
            }

            var isCaptchaValid = await IsCaptchaValid(model.ViewModel.GoogleCaptchaToken);
            if (!isCaptchaValid)
            {
                ModelState.AddModelError(String.Empty, "The captcha is not valid");

                HttpContext.Kentico().PageBuilder().Initialize(page.DocumentID);
                return View(model);
            }

            //Prepares a new user entity using the posted registration data
            var user = new User
            {
                UserName = model.ViewModel.Email,
                Email = model.ViewModel.Email,
                FirstName = model.ViewModel.FirstName,
                LastName = model.ViewModel.LastName,
                Enabled = true
            };

            // Attempts to create the user in the Kentico database
            IdentityResult registerResult = IdentityResult.Failed();
            try
            {
                registerResult = await UserManager.CreateAsync(user, model.ViewModel.Password);
            }
            catch (Exception ex)
            {
                // Logs an error into the Kentico event log if the creation of the user fails

Pedagogy/Views/LogInManager/ConfirmUser.cshtml
@model BaseViewModel

<div class="container mt-5 mb-5">
    <div class="row">
        <h2>Your account has now been activated</h2>
    </div>
</div>

Pedagogy/Views/LogInManager/EmailConfirmationFailed.cshtml
<div class="container mt-5 mb-5">
    <div class="row">
        <h2>@Html.Raw(ResHelper.GetString("LoginManager.EmailConfirmationErrMsg", LocalizationContext.CurrentCulture.CultureCode))</h2>
    </div>
</div>

Pedagogy/Views/LogInManager/FacilityPendingApproval.cshtml
@section styles
{
    @Html.Kentico().PageBuilderStyles()
}

@section scripts
{
    @Html.Kentico().PageBuilderScripts()
}

@Html.Kentico().EditableArea("pendingApproval")

Pedagogy/Views/LogInManager/LogIn.cshtml
@model Pedagogy.Models.BaseViewModel<Pedagogy.Models.LoginManager.LoginViewModel>

<div class="login-area mt-5 mb-5">
    <div class="container">
        <div class="row">
            <div class="mb-3" style="width:400px;">
                <h4>@Model.ViewModel.CheckEmailMsg</h4>
            </div>
            <div class="col-12"></div>
            <div class="login-box">
                <div class="login-header">
                    <h2>Log In</h2>
                </div>
                <div class="login-body">
                    @using (Html.BeginForm("Login", "LoginManager", FormMethod.Post, new { Class = "form-horizontal login-form" }))
                    {
                        @Html.AntiForgeryToken()
                        <div class="invisible">
                            @Html.Hidden("baseNodeJson", Json.Encode(Model.BaseNodeData))
                            @Html.Hidden("returnUrl", Request.QueryString["returnUrl"])
                        </div>
                        <div class="form-group">
                            @if (ViewData.ModelState.Any(x => x.Value.Errors.Any()))
                            {
                                @Html.Raw(HttpUtility.HtmlDecode(Html.ValidationSummary(true, "", new { Class = "text-danger" }).ToHtmlString()))
                            }
                        </div>
                        <div class="form-group m-3">
                            @Html.LabelFor(model => model.ViewModel.UserName, new { Class = "control-label" }) <br />
                            @Html.TextBoxFor(model => model.ViewModel.UserName, new { Id = "user-name", Class = "form-control" })
                            @Html.ValidationMessageFor(model => model.ViewModel.UserName, "", new { Class = "text-danger" })
                        </div>
                        <div class="form-group m-3">
                            @Html.LabelFor(model => model.ViewModel.Password, new { Class = "control-label" })
                            <div class="password-input-container">
                                @Html.PasswordFor(model => model.ViewModel.Password, new { Id = "password", Class = "form-control", Autocomplete = "on" })
                                <i class="fa fa-lg fa-eye pass-visibility-icon show-pass"></i>
                                <i class="fa fa-lg fa-eye-slash pass-visibility-icon hide-pass"></i>
                            </div>
                            @Html.ValidationMessageFor(model => model.ViewModel.Password, "", new { Class = "text-danger" })
                        </div>
                        <div class="form-group m-3">
                            @Html.CheckBoxFor(model => model.ViewModel.RememberMe, new { Id = "remember" })
                            @Html.LabelFor(model => model.ViewModel.RememberMe, new { Class = "control-label" })
                        </div>
                        <div class="form-group mx-2 mt-4">
                            <input type="submit" value="Log In" class="btn btn-primary" id="login-btn" />
                        </div>
                    }
                </div>
                <div class="login-footer">
                    <a href="@Url.Action("Register", "LoginManager")" class="btn btn-outline-primary">Register</a>
                    <a href="@Url.Action("RequestPasswordReset", "LoginManager")" class="btn btn-outline-primary">Forgot Password</a>
                </div>
            </div>
        </div>
    </div>
</div>

Pedagogy/Views/LogInManager/Register.cshtml
@model Pedagogy.Models.BaseViewModel<Pedagogy.Models.LoginManager.RegisterViewModel>

@{
    var key = CMS.DataEngine.SettingsKeyInfoProvider.GetValue("CMSReCaptchaPublicKey");
}

@section styles
{
    @Html.Kentico().PageBuilderStyles()
}

<div class="register-area mt-5 mb-5">
    <div class="container">
        <div class="row mb-4">
            <div style="width:800px;">
                @Html.Kentico().EditableArea("register")
            </div>
        </div>
        <div class="row">
            <div class="register-box">
                <div class="register-header">
                    <h2>Register As Student</h2>
                </div>
                <div class="col-md-10 mx-auto register-body">
                    @using (Html.BeginForm("Register", "LoginManager", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        <div class="invisible">
                            @Html.Hidden("baseNodeJson", Json.Encode(Model.BaseNodeData))
                            @Html.HiddenFor(m => m.ViewModel.GoogleCaptchaToken, new { Id = "GoogleCaptchaToken" })
                            @Html.RadioButtonFor(m => m.ViewModel.RegistrationType, "none", new { Checked = true })
                        </div>
                        <div class="form-validation-container">
                            @if (ViewData.ModelState.Any(x => x.Value.Errors.Any()))
                            {
                                @Html.Raw(HttpUtility.HtmlDecode(Html.ValidationSummary(true, "", new { Class = "text-danger" }).ToHtmlString()))
                            }
                        </div>
                        <div class="form-group row m-2">
                            <div class="col-12 col-md-6 px-2">
                                @Html.LabelFor(model => model.ViewModel.FirstName, new { Class = "control-label" }) <br />
                                @Html.TextBoxFor(model => model.ViewModel.FirstName, new { Id = "first-name", Class = "form-control" })
                                @Html.ValidationMessageFor(model => model.ViewModel.FirstName, "", new { Class = "text-danger" })
                            </div>
                            <div class="col-12 col-md-6 px-2">
                                @Html.LabelFor(model => model.ViewModel.LastName, new { Class = "control-label" }) <br />
                                @Html.TextBoxFor(model => model.ViewModel.LastName, new { Id = "last-name", Class = "form-control" })
                                @Html.ValidationMessageFor(model => model.ViewModel.LastName, "", new { Class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group row m-2">
                            <div class="col-12 col-md-6 px-2">
                                @Html.LabelFor(model => model.ViewModel.Email, new { Class = "control-label" }) <br />
                                @Html.TextBoxFor(model => model.ViewModel.Email, new { Id = "email", Class = "form-control" })
                                @Html.ValidationMessageFor(model => model.ViewModel.Email, "", new { Class = "text-danger" })
                            </div>
                            <div class="col-12 col-md-6 px-2">
                                @Html.LabelFor(model => model.ViewModel.ConfirmEmail, new { Class = "control-label" }) <br />
                                @Html.TextBoxFor(model => model.ViewModel.ConfirmEmail, new { Id = "confirm-email", Class = "form-control" })
                                @Html.ValidationMessageFor(model => model.ViewModel.ConfirmEmail, "", new { Class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group row m-2">
                            <div class="col-12 col-md-6 px-2">
                                @Html.LabelFor(model => model.ViewModel.Password, new { Class = "control-label" }) <br />
                                <div class="password-input-container">
                                    @Html.PasswordFor(model => model.ViewModel.Password, new { Id = "password", Class = "form-control password-input", Autocomplete = "off" })
                                    <i class="fa fa-lg fa-eye pass-visibility-icon show-pass"></i>
                                    <i class="fa fa-lg fa-eye-slash pass-visibility-icon hide-pass"></i>
                                </div>
                                @Html.ValidationMessageFor(model => model.ViewModel.Password, "", new { Class = "text-danger" })
                            </div>
                            <div class="col-12 col-md-6 px-2">
                                @Html.LabelFor(model => model.ViewModel.PasswordConfirmation, new { Class = "control-label" }) <br />
                                <div class="password-input-container">
                                    @Html.PasswordFor(model => model.ViewModel.PasswordConfirmation, new { Id = "confirmation-password", Class = "form-control", Autocomplete = "off" })
                                    <i class="fa fa-lg fa-eye pass-visibility-icon show-pass"></i>
                                    <i class="fa fa-lg fa-eye-slash pass-visibility-icon hide-pass"></i>
                                </div>
                                @Html.ValidationMessageFor(model => model.ViewModel.PasswordConfirmation, "", new { Class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group row m-4">
                            <div class="col-12">
                                @Html.Partial("Partials/_PasswordRequirements")
                            </div>
                        </div>
                        <div class="form-group d-flex justify-content-center mt-5">
                            <input type="submit" value="Register" class="btn btn-primary" id="register-btn" />
                        </div>
                    }
                </div>
                <div class="d-flex justify-content-around mt-5">
                    <a href="@Url.Action("RequestPasswordReset", "LoginManager")" class="btn btn-outline-primary">Forgot Password</a>
                    <a href="@Url.Action("Login", "LoginManager")" class="btn btn-outline-primary">Log In</a>
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts{
    @Html.Kentico().PageBuilderScripts()
    <script src="https://www.google.com/recaptcha/api.js?render=@key"></script>
    <script>
        $(document).ready(function () {
            $("#confirmation-password").on('input', function () {
                grecaptcha.ready(function () {
                    grecaptcha.execute('@key', { action: 'register' }).then(function (token) {
                        $("#GoogleCaptchaToken").val(token);
                    });
                });
            });
        });
    </script>
}

Pedagogy/Views/LogInManager/RequestPasswordReset.cshtml
@model BaseViewModel<Pedagogy.Models.LoginManager.RequestPasswordResetViewModel>

<div class="reset-password-area mt-5 mb-5">
    <div class="container">
        <div class="row">
            <div class="mb-3" style="width:400px;">
                @if (!string.IsNullOrEmpty(Model.ViewModel.UserNotFoundErrMsg))
                {
                    <p style="font-size:18px;" class="text-danger">@Model.ViewModel.UserNotFoundErrMsg</p>
                }
                @if (!string.IsNullOrEmpty(Model.ViewModel.CheckEmailMsg))
                {
                    <p style="font-size:18px;">@Model.ViewModel.CheckEmailMsg</p>
                }
            </div>
            <div class="col-12"></div>
            <div class="reset-password-box">
                <div class="reset-password-header">
                    <h2>Password Reset</h2>
                </div>
                <div class="reset-password-body">
                    @using (Html.BeginForm(new { Class = "form-horizontal password-reset-form" }))
                    {
                        @Html.AntiForgeryToken()
                        <div class="invisible">
                            @Html.Hidden("baseNodeJson", Json.Encode(Model.BaseNodeData))
                        </div>
                        <div class="form-group">
                            @if (ViewData.ModelState.Any(x => x.Value.Errors.Any()))
                            {
                                @Html.Raw(HttpUtility.HtmlDecode(Html.ValidationSummary(true, "", new { Class = "text-danger" }).ToHtmlString()))
                            }
                        </div>
                        <div class="form-group">
                            @Html.ValidationMessageFor(model => model.ViewModel.Email, "", new { Class = "text-danger" }) <br />
                            @Html.LabelFor(model => model.ViewModel.Email, new { Class = "control-label" }) <br />
                            @Html.TextBoxFor(model => model.ViewModel.Email, new { Id = "email", Class = "form-control" })
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Send Password Reset Link" class="btn btn-primary" id="reset-password-btn" />
                        </div>
                    }
                </div>
                <div class="reset-password-footer">
                    <div class="login-btn">
                        <a href="@Url.Action("Login", "LoginManager")" class="btn btn-outline-primary">Log In</a>
                    </div>
                    <div class="register-btn">
                        <a href="@Url.Action("Register", "LoginManager")" class="btn btn-outline-primary">Register</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Pedagogy/Views/LogInManager/ResetPasswordInvalid.cshtml
<div class="container my-5">
    <div class="row">
        <h4>@Html.Raw(ResHelper.GetString("LoginManager.ResetPassword.ValidationErrMsg", LocalizationContext.CurrentCulture.CultureCode))</h4>
    </div>
</div>